# Local development (docker-compose in ../../../infra)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tvu_ticket
    username: tvu
    password: tvu
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    vn.edu.tvu: DEBUG
